[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "attributes_first"
quote_style = "double"
number_underscore = "thousands"
override_spacing = true
wrap_comments = true
ignore = []